branches:
  only:
  - pelican
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - make publish
notifications:
  slack: dunderlabs:Gkx9FdRZXO5pfbiuHOy4vB3W
  email:
    on_success: never
    on_failure: never
env:
  global:
    secure: "sQlDxP0EYIQFpWUH2BzlTxSYQ47/o9e/hvoaiBIShiCWXw3KdEUZXzNW2dk/99jnVdZKDMuHcSAII4iMDSJqI2zEsZRSZldoyjJ1p6ufXee5mhH9bkjsGg9A6wevWitHcmVSAszGv5PdYX0WHZL438vvM3wPNXprienkPNJLnEiY6B+S18tkKBGRAW6ENWni1PP/h4XFTFlwkxREBwZCIC8aNl1yW4vaIT1JkmSt+N/QODvbQDHZw+5LtNVlhpWfBFJN0XTuaFH9NYIt9cV3OxLQwoOVrYGb7lTrTsp7l20oieLd0jrui72uhl4+fBVLD/WJtsMSmNwKqmdwfxfZHG+9rIl4rbCsKB/dwflfKuYN4iBMG7BBolefaH3Y58SZEwMLCcS3hEYE8xLcuhR170q2H38sTvp+77w5m935Zg3UBD/iav+P2d0XrFvJFkbUtuLZfenOEnlZ4/BDJTw9s/PEmGHLBvy1Yljexlja0zNYuDUzrxxOsMmEFsPoc6INsQ+hit3Qb3G+AyQJxM6UB9kwXE1r59m8AsAwAwiXEFNrECdNqqZ2f27XD38mKCLDJpQjq5WVMaxzDR18H+qzgxanRcl7q/GifBIeaNpeqrTHtDOmorurIgkx9EFQ2XjeREfzVKrntmXpj4d/IlNfdFLgddWH0Ur3yLNCupTdgXY="
before_install:
  - git submodule update --init --recursive
after_success: bash deploy.sh
